name: build
on:
  push:
    branches:
      - develop
    paths:
      - src/*/README.md
      - src/*/manifest.json
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .
          git diff --staged --quiet || git commit -m "dist: merge $GITHUB_SHA"
          git push