name: release
on:
  push:
    branches:
      - release
    paths:
      - config/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .
          git diff --staged --quiet || git commit -m "chore(dist): merge $GITHUB_SHA"

          git checkout develop
          git merge release

          git push --all
